# SPDX-FileCopyrightText: 2025 Stefan Hackenberg
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["pdm.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Stefan Hackenberg"
SPDX-License-Identifier = "CC0-1.0"
